<?php

/**
 * @file
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function ds_recaptcha_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if(\Drupal::currentUser()->hasPermission('bypass ds_recaptcha')){
    return;
  }

  $config = \Drupal::configFactory()->get('ds_recaptcha.config');

  $form_ids = explode(',', $config->get('form_ids'));
  if(!in_array($form_id, $form_ids)){
    return;
  }

  $form['#attributes']['data-recaptcha-id'] = $form_id;
  $div_id = $form['#form_id'] . '-captcha';
  // Wrapper for reCAPTCHA widget.
  $form['actions']['captcha']['#markup'] = '<div id="' . $div_id . '" class="captcha captcha-wrapper"></div>';
  $form['actions']['captcha']['#weight'] = -1;
  // Helper JS.
  $form['#attached']['drupalSettings']['ds_recaptcha']['sitekey'] = $config->get('site_key');
  foreach($form_ids as $id){
    $form['#attached']['drupalSettings']['ds_recaptcha']['form_ids'][$id] = $id;
  }
  $form['#attached']['library'][] = 'ds_recaptcha/ds_recaptcha';
  return $form;
}
